name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Run setup and tests
      run: |
        # Debug info
        pwd
        ls -la
        
        # Setup
        ./setup.sh -y
        
        # Activate and test with PYTHONPATH
        source .venv/bin/activate
        export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        
        # Run CLI directly via Python first to test
        python -m commands --version
        
        # Now try the cli command
        cli --version || echo "CLI command failed, trying direct Python"
        
        # Run tests directly via Python
        python -m commands dev all || echo "Tests via module failed"
        
        # Alternative: run dev checks directly
        black . --check
        ruff check .
        mypy commands
        pytest