name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Run setup and tests
      run: |
        # Setup
        ./setup.sh -y
        
        # Activate and test
        source .venv/bin/activate
        cli --version
        cli dev all